### ISSUE TITLE
mc_task: ImportError: cannot import name 'Ty' from 'discopy'

### ISSUE THREAD

**Issue by dtchang** [CQCL/qnlp_lorenz_etal_2021_resources#3]
The code is not compatible with the current version of DisCoPy (1.0.0), which has major package changes (e.g,, multiple Ty).

Please update asap. Thanks.

**Comment by AnnaNPearson** [comment]
These notebooks are compatible with the versions of the packages listed under code requirements. Due to these packages being frequently updated we do not guarantee compatibility with newer versions of them. Please see the QNLP library lambeq with accompanying documentation and examples, which is more up to date, and may be more appropriate for your needs. 

Documentation: https://cqcl.github.io/lambeq/index.html  
Paper: https://arxiv.org/pdf/2110.04236.pdf

**Comment by dtchang** [comment]
No problem. I tried lambeq 0.2.8 which has discopy 0.5.0. The code is compatible.
